export const SAVE_TODO_REQUEST = "SAVE_TODO_REQUEST";
export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const TODO_SUCCESS = "TODO_SUCCESS";
export const TODO_FAILURE = "TODO_FAILURE";


